-- CreateEnum
CREATE TYPE "COMPLETIONSTATUS" AS ENUM ('PENDING', 'COMPLETED', 'PROGRESS', 'RETAKE_RECOMMENDED');

-- AlterTable
ALTER TABLE "CourseSlides" ADD COLUMN     "completionStatus" "COMPLETIONSTATUS" NOT NULL DEFAULT 'PENDING';
